In [1]:
import numpy as np
import cv2

cascade_file = r"C:\Users\tench\Anaconda projects\haarcascades/haarcascade_frontalface_alt.xml"
cascade = cv2.CascadeClassifier(cascade_file)

cap = cv2.VideoCapture(0)
ret = cap.set(3, 1280)
ret = cap.set(4, 720)
# print('width:' + str(cap.get(3)) + ', height:' + str(cap.get(4)))

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    image_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    front_face_list = cascade.detectMultiScale(image_gray, minSize = (30, 30))
    print(front_face_list)

    # Display the resulting frame
    if len(front_face_list):
        for (x,y,w,h) in front_face_list:
            print("[x,y] = %d,%d [w,h] = %d,%d" %(x, y, w, h))
            cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 0, 255), thickness=5)
        cv2.imshow('image', frame)

    else:
        cv2.imshow('image', frame)
        print('not detected')
        
    if cv2.waitKey(1) & 0xFF == ord('q'):
        # When everything done, release the capture
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

[[373 225 339 339]]
[x,y] = 373,225 [w,h] = 339,339
[[361 238 319 319]]
[x,y] = 361,238 [w,h] = 319,319
[[364 242 318 318]]
[x,y] = 364,242 [w,h] = 318,318
[[361 239 315 315]]
[x,y] = 361,239 [w,h] = 315,315
[[351 231 332 332]]
[x,y] = 351,231 [w,h] = 332,332
[[354 221 347 347]]
[x,y] = 354,221 [w,h] = 347,347
[[344 224 342 342]]
[x,y] = 344,224 [w,h] = 342,342
[[347 218 340 340]]
[x,y] = 347,218 [w,h] = 340,340
[[346 224 338 338]]
[x,y] = 346,224 [w,h] = 338,338
[[340 237 335 335]]
[x,y] = 340,237 [w,h] = 335,335
[[361 249 318 318]]
[x,y] = 361,249 [w,h] = 318,318
[[389 276 245 245]]
[x,y] = 389,276 [w,h] = 245,245
()
not detected
()
not detected
()
not detected
()
not detected
()
not detected
()
not detected
()
not detected
[[550 404  47  47]]
[x,y] = 550,404 [w,h] = 47,47
[[380 258 338 338]]
[x,y] = 380,258 [w,h] = 338,338
[[391 253 333 333]]
[x,y] = 391,253 [w,h] = 333,333
[[392 252 326 326]]
[x,y] = 392,252 [w,h] = 326,326
[[380 240 341 341]]
[x,y] = 380,240 [w,h] = 341,341
[[373 